import SideBar from '@/components/SideBar/SideBar';

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "YouTube",
    description: "Generated by create next app",
};

export default function SideBarLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <SideBar></SideBar>
            {children}
        </>
    );
}
