import type { Metadata } from "next";
import '../globals.css';

import { Roboto } from 'next/font/google';
import { Suspense } from 'react';

import CtaLogin from '@/components/CtaLogin';
import Loading from '@/components/Loading';
import MobieBottomNav from '@/components/MobieBottomNav/MobieBottomNav';
import { Toaster } from '@/components/ui/toaster';
import Header from '@/feature/home/components/Header/Header';
import { ClerkProvider } from '@clerk/nextjs';

const roboto = Roboto({
    weight: ["400", "700", "500"],
    style: ["normal", "italic"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "YouTube",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html
                lang="en"
                className={roboto.className}
                suppressHydrationWarning={true}
            >
                <body className="overflow-x-hidden !transition-colors !duration-500">
                    <Toaster />
                    <Suspense fallback={<Loading />}>
                        <Header></Header>
                    </Suspense>
                    <main>{children}</main>
                    <MobieBottomNav></MobieBottomNav>
                    <CtaLogin></CtaLogin>
                </body>
            </html>
        </ClerkProvider>
    );
}
