import type { Metadata } from "next";
import './globals.css';

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '700' , '500'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
    title: "YouTube",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.className}>
            <body>{children}</body>
        </html>
    );
}
